-- Co-Helper now uses a single canonical schema.
--
-- Empty database:
--   cd backend && npm run db:setup
--
-- Wipe existing tables and start from the core model
-- (users, workspaces, clients, projects, collaborators, settings):
--   cd backend && npm run db:reset
